# Список категорий+
GET http://localhost:3000/api/categories HTTP/1.1

###

# Поиск+
GET http://localhost:3000/api/search?query=Рок HTTP/1.1

###

# Запрашивает все публикации+
GET http://localhost:3000/api/articles HTTP/1.1

###

# Запрашивает публикацию с идентификатором :id+

GET http://localhost:3000/api/articles/flDlvV HTTP/1.1

###

# Удаление публикации с идентификатором :id+

DELETE http://localhost:3000/api/articles/flDlvV HTTP/1.1

###

# Добавление новой публикации+

POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "id": "709m78",
  "title": "Новая публикация",
  "createdDate": "2020-12-23",
  "announce": "Золотое сечение — соотношение двух величин, гармоническая пропорция. Рок-музыка всегда ассоциировалась с протестами. Так ли это на самом деле? Сотрясение мозга – очень серьезно. Пора перестать восхищаться теми, кто возвращается в поле после травм головы. Он написал больше 30 хитов.",
  "fullText": "Медведев сейчас так хорош, что обводит даже одноручным бэкхендом. Как начать действовать? Для начала просто соберитесь. Процессор заслуживает особого внимания. Он обязательно понравится геймерам со стажем. Этот смартфон — настоящая находка. Большой и яркий экран, мощнейший процессор — всё это в небольшом гаджете. Достичь успеха помогут ежедневные повторения. Простые ежедневные упражнения помогут достичь успеха. Сотрясение мозга – очень серьезно. Пора перестать восхищаться теми, кто возвращается в поле после травм головы. Леброн пробежал половину площадки с мячом в руках и забил сверху. Разве это не пробежка? Программировать не настолько сложно, как об этом говорят.",
  "category": [
    "Спорт"
  ],
  "comments": [
    {
      "id": "BQ-ocu",
      "text": "Давно не пользуюсь стационарными компьютерами. Ноутбуки победили.\r"
    },
    {
      "id": "Pcpf7f",
      "text": "Согласен с автором!\r Мне кажется или я уже читал это где-то?\r"
    }
  ]
}

###

# Обновление объявления+

PUT http://localhost:3000/api/articles/709m78 HTTP/1.1
Content-Type: application/json

{
  "id": "709m78",
  "title": "Новая публикация2",
  "createdDate": "2020-12-24",
  "announce": "Золотое сечение — соотношение двух величин, гармоническая пропорция. Рок-музыка всегда ассоциировалась с протестами. Так ли это на самом деле? Сотрясение мозга – очень серьезно. Пора перестать восхищаться теми, кто возвращается в поле после травм головы. Он написал больше 30 хитов.",
  "fullText": "Медведев сейчас так хорош, что обводит даже одноручным бэкхендом. Как начать действовать? Для начала просто соберитесь. Процессор заслуживает особого внимания. Он обязательно понравится геймерам со стажем. Этот смартфон — настоящая находка. Большой и яркий экран, мощнейший процессор — всё это в небольшом гаджете. Достичь успеха помогут ежедневные повторения. Простые ежедневные упражнения помогут достичь успеха. Сотрясение мозга – очень серьезно. Пора перестать восхищаться теми, кто возвращается в поле после травм головы. Леброн пробежал половину площадки с мячом в руках и забил сверху. Разве это не пробежка? Программировать не настолько сложно, как об этом говорят.",
  "category": [
    "Спорт"
  ],
  "comments": [
    {
      "id": "BQ-ocu",
      "text": "Давно не пользуюсь стационарными компьютерами. Ноутбуки победили.\r"
    },
    {
      "id": "Pcpf7f",
      "text": "Согласен с автором!\r Мне кажется или я уже читал это где-то?\r"
    }
  ]
}

###

# Список комментариев+

GET http://localhost:3000/api/articles/709m78/comments HTTP/1.1

###

# Удаляет комментарий+

DELETE http://localhost:3000/api/articles/709m78/comments/BQ-ocu HTTP/1.1

###

# Добавляет новый комментарий к публикации+

POST http://localhost:3000/api/articles/709m78/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это новый комментарий",
  "id": "BQ-ocu"
}